# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  pull_request:
    branches: [main, development]
    paths:
        - 'VOCABULARIES/**'
  workflow_dispatch:

name: createValidationTableAndCheck

jobs:
  createValidationTableAndCheck:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install dependencies
        shell: Rscript {0}
        run: |
          install.packages("remotes")
          remotes::install_github("FinOMOP/ROMOPMappingTools", ref = "towards_v2", force = TRUE)

      - name: Copy OMOP_vocabularies from private repo       
        uses: robinraju/release-downloader@v1.7
        with:
          repository: 'FinOMOP/OMOP_vocabularies'
          latest: true
          fileName: 'input_omop_vocabulary.zip'
          out-file-path: 'OMOP_vocabularies/data'
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: unzip input_omop_vocabulary.zip
        working-directory: input_data
        shell: bash
        run: |
         rm input_omop_vocabulary/*
         unzip input_omop_vocabulary.zip

      - name: Run R script
        working-directory: .github/scripts
        shell: Rscript {0}
        run: source("createValidationTableAndChecks.R")

      - name: Upload results to artifacts
        uses: actions/upload-artifact@v3
        with:
          name: validationResults
          path: output_data/validationResults
          retention-days: 1