# Action to validate vocabularies
#
# On a PR to development if any changes are detected in the VOCABULARIES directory then
# - Check the changes in the vocabularies are correct
# - Reformat the Usage files if they have been changed
# - Update the VOCABULARIES_VALIDATION_STATUS.md file
# - If errors are found, fail the workflow
#
on:
  pull_request:
    branches: [development]
    paths:
      - 'VOCABULARIES/**'
  workflow_dispatch:

name: validateVocabularies

jobs:
  validateVocabularies:
    runs-on: ubuntu-latest
    env:
      BUILD_DASHBOARD: FALSE
      BUILD_VOCABULARIES: FALSE
      #
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      #
    permissions:
      contents: write      # Allows pushing to the repository
      pull-requests: write # If you need to comment on PRs
    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install dependencies
        shell: Rscript {0}
        run: |
          install.packages("remotes")
          remotes::install_github("FinOMOP/ROMOPMappingTools", force = TRUE)

      - name: Copy OMOP_vocabularies from private repo       
        uses: robinraju/release-downloader@v1.7
        with:
          repository: 'FinOMOP/OMOP_vocabularies'
          latest: true
          fileName: 'input_omop_vocabulary.zip'
          out-file-path: 'input_data'
          token: ${{ secrets.TOKEN_OMOP_VOCABULARIES }}

      - name: unzip input_omop_vocabulary.zip
        working-directory: input_data
        shell: bash
        run: |
         unzip -o input_omop_vocabulary.zip

      - name: Run R script
        shell: Rscript {0}
        run: source("dev/scripts/runAllGitHubAction.R")

      - name: Read final status
        id: read_status
        run: |
          FINAL_STATUS=$(cat /tmp/FINAL_STATUS.txt)
          echo "FINAL_STATUS=$FINAL_STATUS" >> $GITHUB_ENV

      - name: Commit and push validation status
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          # Get the current branch name
          branch_name="${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}"
          # Fetch and merge changes
          git fetch origin ${branch_name}
          git checkout ${branch_name}
          git pull origin ${branch_name}
          # Make changes and push
          git add VOCABULARIES/*
          git commit -m "Update validation status [skip ci]" || echo "No changes to commit"
          git push origin ${branch_name}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: If any error fail the workflow
        run: |
          cat VOCABULARIES/VOCABULARIES_VALIDATION_STATUS.md
          echo "Final status is Error"
          exit 1
